# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cba04331a0b08ef9cd1cccd784caa096e4a18afb48ab2743bde7f3f4c3df710063e117b32638913175b986ae8549993b07622f33e7568044793284da51c0510c

test:
  secret_key_base: 0317822b137d49f8e91ecff3e1dfe0fe4e3ccd0e1313c5cd4c21fc0a45c364b2748c0b4f39e0059db478e18bbda9bfa1650138258faa9329772910f4c0c5448b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
