Tanuki.find_or_create_by(pic: 'pic/4685.jpg',race: 'タヌキ',photoby: '663highland')
Tanuki.find_or_create_by(pic: 'pic/8462.jpg',race: 'タヌキ',photoby: '663highland')
Tanuki.find_or_create_by(pic: 'pic/2998.jpg',race: 'タヌキ',photoby: 'Dennis Irrgang')
Tanuki.find_or_create_by(pic: 'pic/1973.jpg',race: 'タヌキ',photoby: 'Mckinlayr')
Tanuki.find_or_create_by(pic: 'pic/7763.jpg',race: 'アライグマ',photoby: 'Raymond Shobe')
Tanuki.find_or_create_by(pic: 'pic/6785.jpg',race: 'アライグマ',photoby: 'Korall')
Tanuki.find_or_create_by(pic: 'pic/3939.jpg',race: 'アライグマ',photoby: 'Fascinating Universe')
Tanuki.find_or_create_by(pic: 'pic/4468.jpg',race: 'アライグマ',photoby: 'Everglades NPS')
Tanuki.find_or_create_by(pic: 'pic/7983.jpg',race: 'レッサーパンダ',photoby: 'Tom Raftery')
Tanuki.find_or_create_by(pic: 'pic/5689.jpg',race: 'レッサーパンダ',photoby: 'Brunswyk')
Tanuki.find_or_create_by(pic: 'pic/9100.jpg',race: 'レッサーパンダ',photoby: '山下 良子')
Tanuki.find_or_create_by(pic: 'pic/2517.jpg',race: 'レッサーパンダ',photoby: 'Catatine')
Tanuki.find_or_create_by(pic: 'pic/5000.jpg',race: 'ハクビシン',photoby: 'Denise Chan')
Tanuki.find_or_create_by(pic: 'pic/7198.jpg',race: 'アナグマ',photoby: 'OpenCage')
Tanuki.find_or_create_by(pic: 'pic/6388.jpg',race: 'メガネザル',photoby: 'Sakurai Midori')
Tanuki.find_or_create_by(pic: 'pic/1999.jpg',race: 'タヌキ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/3100.jpg',race: 'アライグマ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/3258.jpg',race: 'ミーアキャット',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/5012.jpg',race: 'マングース',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/3329.jpg',race: 'タヌキ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/7575.jpg',race: 'タヌキ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/8631.jpg',race: 'タヌキ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/6933.jpg',race: 'タヌキ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/5513.jpg',race: 'タヌキ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/3447.jpg',race: 'タヌキ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/6337.jpg',race: 'アナグマ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/6891.jpg',race: 'アナグマ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/8979.jpg',race: 'パンダ',photoby: 'ミニネットZOO',url: 'http://mininetzoo.com/index.html')
Tanuki.find_or_create_by(pic: 'pic/8937.jpg',race: 'タヌキ',photoby: 'mamameron')
Tanuki.find_or_create_by(pic: 'pic/1045.jpg',race: 'タヌキ',photoby: '寝太郎')
Tanuki.find_or_create_by(pic: 'pic/2260.jpg',race: 'アライグマ',photoby: 'oclave')
Tanuki.find_or_create_by(pic: 'pic/4772.jpg',race: 'タヌキ',photoby: 'みのやん')
Tanuki.find_or_create_by(pic: 'pic/3000.jpg',race: 'タヌキ',photoby: 'Tambako the Jaguar')
Tanuki.find_or_create_by(pic: 'pic/3001.jpg',race: 'タヌキ',photoby: 'Tambako the Jaguar')
Tanuki.find_or_create_by(pic: 'pic/3889.jpg',race: 'アライグマ',photoby: 'Ruy Alvarez')
Tanuki.find_or_create_by(pic: 'pic/4648.jpg',race: 'アライグマ',photoby: 'Bill Bouton')
Tanuki.find_or_create_by(pic: 'pic/8710.jpg',race: 'ミーアキャット',photoby: 'Böhringer Friedrich')
Tanuki.find_or_create_by(pic: 'pic/6935.jpg',race: 'ウシ',photoby: 'ars.usda.gov')
Tanuki.find_or_create_by(pic: 'pic/7445.jpg',race: 'ネコ',photoby: 't-miki')
Tanuki.find_or_create_by(pic: 'pic/2536.jpg',race: 'イヌ',photoby: 'Janette Fuller')
